// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constants.proto

package rm_local_ctrl;

public final class Constants {
  private Constants() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code rm_local_ctrl.Status}
   */
  public enum Status
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Success = 0;</code>
     */
    Success(0),
    /**
     * <code>InvalidSecScheme = 1;</code>
     */
    InvalidSecScheme(1),
    /**
     * <code>InvalidProto = 2;</code>
     */
    InvalidProto(2),
    /**
     * <code>TooManySessions = 3;</code>
     */
    TooManySessions(3),
    /**
     * <code>InvalidArgument = 4;</code>
     */
    InvalidArgument(4),
    /**
     * <code>InternalError = 5;</code>
     */
    InternalError(5),
    /**
     * <code>CryptoError = 6;</code>
     */
    CryptoError(6),
    /**
     * <code>InvalidSession = 7;</code>
     */
    InvalidSession(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Success = 0;</code>
     */
    public static final int Success_VALUE = 0;
    /**
     * <code>InvalidSecScheme = 1;</code>
     */
    public static final int InvalidSecScheme_VALUE = 1;
    /**
     * <code>InvalidProto = 2;</code>
     */
    public static final int InvalidProto_VALUE = 2;
    /**
     * <code>TooManySessions = 3;</code>
     */
    public static final int TooManySessions_VALUE = 3;
    /**
     * <code>InvalidArgument = 4;</code>
     */
    public static final int InvalidArgument_VALUE = 4;
    /**
     * <code>InternalError = 5;</code>
     */
    public static final int InternalError_VALUE = 5;
    /**
     * <code>CryptoError = 6;</code>
     */
    public static final int CryptoError_VALUE = 6;
    /**
     * <code>InvalidSession = 7;</code>
     */
    public static final int InvalidSession_VALUE = 7;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return Success;
        case 1: return InvalidSecScheme;
        case 2: return InvalidProto;
        case 3: return TooManySessions;
        case 4: return InvalidArgument;
        case 5: return InternalError;
        case 6: return CryptoError;
        case 7: return InvalidSession;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            @Override
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return StatusVerifier.INSTANCE;
    }

    private static final class StatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
            @Override
            public boolean isInRange(int number) {
              return Status.forNumber(number) != null;
            }
          };

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rm_local_ctrl.Status)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
