// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: esp_rmaker_user_mapping.proto

package rainmaker;

public final class EspRmakerUserMapping {
  private EspRmakerUserMapping() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code rainmaker.RMakerConfigStatus}
   */
  public enum RMakerConfigStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Success = 0;</code>
     */
    Success(0),
    /**
     * <code>InvalidParam = 1;</code>
     */
    InvalidParam(1),
    /**
     * <code>InvalidState = 2;</code>
     */
    InvalidState(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Success = 0;</code>
     */
    public static final int Success_VALUE = 0;
    /**
     * <code>InvalidParam = 1;</code>
     */
    public static final int InvalidParam_VALUE = 1;
    /**
     * <code>InvalidState = 2;</code>
     */
    public static final int InvalidState_VALUE = 2;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RMakerConfigStatus valueOf(int value) {
      return forNumber(value);
    }

    public static RMakerConfigStatus forNumber(int value) {
      switch (value) {
        case 0: return Success;
        case 1: return InvalidParam;
        case 2: return InvalidState;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RMakerConfigStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RMakerConfigStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RMakerConfigStatus>() {
            @Override
            public RMakerConfigStatus findValueByNumber(int number) {
              return RMakerConfigStatus.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return RMakerConfigStatusVerifier.INSTANCE;
    }

    private static final class RMakerConfigStatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new RMakerConfigStatusVerifier();
            @Override
            public boolean isInRange(int number) {
              return RMakerConfigStatus.forNumber(number) != null;
            }
          };

    private final int value;

    private RMakerConfigStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rainmaker.RMakerConfigStatus)
  }

  /**
   * Protobuf enum {@code rainmaker.RMakerConfigMsgType}
   */
  public enum RMakerConfigMsgType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>TypeCmdSetUserMapping = 0;</code>
     */
    TypeCmdSetUserMapping(0),
    /**
     * <code>TypeRespSetUserMapping = 1;</code>
     */
    TypeRespSetUserMapping(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TypeCmdSetUserMapping = 0;</code>
     */
    public static final int TypeCmdSetUserMapping_VALUE = 0;
    /**
     * <code>TypeRespSetUserMapping = 1;</code>
     */
    public static final int TypeRespSetUserMapping_VALUE = 1;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RMakerConfigMsgType valueOf(int value) {
      return forNumber(value);
    }

    public static RMakerConfigMsgType forNumber(int value) {
      switch (value) {
        case 0: return TypeCmdSetUserMapping;
        case 1: return TypeRespSetUserMapping;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RMakerConfigMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RMakerConfigMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RMakerConfigMsgType>() {
            @Override
            public RMakerConfigMsgType findValueByNumber(int number) {
              return RMakerConfigMsgType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return RMakerConfigMsgTypeVerifier.INSTANCE;
    }

    private static final class RMakerConfigMsgTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new RMakerConfigMsgTypeVerifier();
            @Override
            public boolean isInRange(int number) {
              return RMakerConfigMsgType.forNumber(number) != null;
            }
          };

    private final int value;

    private RMakerConfigMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rainmaker.RMakerConfigMsgType)
  }

  public interface CmdSetUserMappingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rainmaker.CmdSetUserMapping)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string UserID = 1;</code>
     */
    String getUserID();
    /**
     * <code>string UserID = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIDBytes();

    /**
     * <code>string SecretKey = 2;</code>
     */
    String getSecretKey();
    /**
     * <code>string SecretKey = 2;</code>
     */
    com.google.protobuf.ByteString
        getSecretKeyBytes();
  }
  /**
   * Protobuf type {@code rainmaker.CmdSetUserMapping}
   */
  public  static final class CmdSetUserMapping extends
      com.google.protobuf.GeneratedMessageLite<
          CmdSetUserMapping, CmdSetUserMapping.Builder> implements
      // @@protoc_insertion_point(message_implements:rainmaker.CmdSetUserMapping)
      CmdSetUserMappingOrBuilder {
    private CmdSetUserMapping() {
      userID_ = "";
      secretKey_ = "";
    }
    public static final int USERID_FIELD_NUMBER = 1;
    private String userID_;
    /**
     * <code>string UserID = 1;</code>
     */
    @Override
    public String getUserID() {
      return userID_;
    }
    /**
     * <code>string UserID = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userID_);
    }
    /**
     * <code>string UserID = 1;</code>
     */
    private void setUserID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userID_ = value;
    }
    /**
     * <code>string UserID = 1;</code>
     */
    private void clearUserID() {
      
      userID_ = getDefaultInstance().getUserID();
    }
    /**
     * <code>string UserID = 1;</code>
     */
    private void setUserIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userID_ = value.toStringUtf8();
    }

    public static final int SECRETKEY_FIELD_NUMBER = 2;
    private String secretKey_;
    /**
     * <code>string SecretKey = 2;</code>
     */
    @Override
    public String getSecretKey() {
      return secretKey_;
    }
    /**
     * <code>string SecretKey = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getSecretKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(secretKey_);
    }
    /**
     * <code>string SecretKey = 2;</code>
     */
    private void setSecretKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secretKey_ = value;
    }
    /**
     * <code>string SecretKey = 2;</code>
     */
    private void clearSecretKey() {
      
      secretKey_ = getDefaultInstance().getSecretKey();
    }
    /**
     * <code>string SecretKey = 2;</code>
     */
    private void setSecretKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secretKey_ = value.toStringUtf8();
    }

    public static CmdSetUserMapping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdSetUserMapping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdSetUserMapping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdSetUserMapping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdSetUserMapping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdSetUserMapping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdSetUserMapping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdSetUserMapping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdSetUserMapping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CmdSetUserMapping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdSetUserMapping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdSetUserMapping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(CmdSetUserMapping prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code rainmaker.CmdSetUserMapping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CmdSetUserMapping, Builder> implements
        // @@protoc_insertion_point(builder_implements:rainmaker.CmdSetUserMapping)
        CmdSetUserMappingOrBuilder {
      // Construct using rainmaker.EspRmakerUserMapping.CmdSetUserMapping.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string UserID = 1;</code>
       */
      @Override
      public String getUserID() {
        return instance.getUserID();
      }
      /**
       * <code>string UserID = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getUserIDBytes() {
        return instance.getUserIDBytes();
      }
      /**
       * <code>string UserID = 1;</code>
       */
      public Builder setUserID(
          String value) {
        copyOnWrite();
        instance.setUserID(value);
        return this;
      }
      /**
       * <code>string UserID = 1;</code>
       */
      public Builder clearUserID() {
        copyOnWrite();
        instance.clearUserID();
        return this;
      }
      /**
       * <code>string UserID = 1;</code>
       */
      public Builder setUserIDBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIDBytes(value);
        return this;
      }

      /**
       * <code>string SecretKey = 2;</code>
       */
      @Override
      public String getSecretKey() {
        return instance.getSecretKey();
      }
      /**
       * <code>string SecretKey = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getSecretKeyBytes() {
        return instance.getSecretKeyBytes();
      }
      /**
       * <code>string SecretKey = 2;</code>
       */
      public Builder setSecretKey(
          String value) {
        copyOnWrite();
        instance.setSecretKey(value);
        return this;
      }
      /**
       * <code>string SecretKey = 2;</code>
       */
      public Builder clearSecretKey() {
        copyOnWrite();
        instance.clearSecretKey();
        return this;
      }
      /**
       * <code>string SecretKey = 2;</code>
       */
      public Builder setSecretKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSecretKeyBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rainmaker.CmdSetUserMapping)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CmdSetUserMapping();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "userID_",
              "secretKey_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<CmdSetUserMapping> parser = PARSER;
          if (parser == null) {
            synchronized (CmdSetUserMapping.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:rainmaker.CmdSetUserMapping)
    private static final CmdSetUserMapping DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new CmdSetUserMapping();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CmdSetUserMapping.class, DEFAULT_INSTANCE);
    }
    public static CmdSetUserMapping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CmdSetUserMapping> PARSER;

    public static com.google.protobuf.Parser<CmdSetUserMapping> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RespSetUserMappingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rainmaker.RespSetUserMapping)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
     */
    RMakerConfigStatus getStatus();

    /**
     * <code>string NodeId = 2;</code>
     */
    String getNodeId();
    /**
     * <code>string NodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();
  }
  /**
   * Protobuf type {@code rainmaker.RespSetUserMapping}
   */
  public  static final class RespSetUserMapping extends
      com.google.protobuf.GeneratedMessageLite<
          RespSetUserMapping, RespSetUserMapping.Builder> implements
      // @@protoc_insertion_point(message_implements:rainmaker.RespSetUserMapping)
      RespSetUserMappingOrBuilder {
    private RespSetUserMapping() {
      nodeId_ = "";
    }
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
     */
    @Override
    public RMakerConfigStatus getStatus() {
      RMakerConfigStatus result = RMakerConfigStatus.forNumber(status_);
      return result == null ? RMakerConfigStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
     */
    private void setStatus(RMakerConfigStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private String nodeId_;
    /**
     * <code>string NodeId = 2;</code>
     */
    @Override
    public String getNodeId() {
      return nodeId_;
    }
    /**
     * <code>string NodeId = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nodeId_);
    }
    /**
     * <code>string NodeId = 2;</code>
     */
    private void setNodeId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeId_ = value;
    }
    /**
     * <code>string NodeId = 2;</code>
     */
    private void clearNodeId() {
      
      nodeId_ = getDefaultInstance().getNodeId();
    }
    /**
     * <code>string NodeId = 2;</code>
     */
    private void setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeId_ = value.toStringUtf8();
    }

    public static RespSetUserMapping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespSetUserMapping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespSetUserMapping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespSetUserMapping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespSetUserMapping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespSetUserMapping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespSetUserMapping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespSetUserMapping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespSetUserMapping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RespSetUserMapping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespSetUserMapping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespSetUserMapping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RespSetUserMapping prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code rainmaker.RespSetUserMapping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RespSetUserMapping, Builder> implements
        // @@protoc_insertion_point(builder_implements:rainmaker.RespSetUserMapping)
        RespSetUserMappingOrBuilder {
      // Construct using rainmaker.EspRmakerUserMapping.RespSetUserMapping.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
       */
      @Override
      public RMakerConfigStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
       */
      public Builder setStatus(RMakerConfigStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.rainmaker.RMakerConfigStatus Status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>string NodeId = 2;</code>
       */
      @Override
      public String getNodeId() {
        return instance.getNodeId();
      }
      /**
       * <code>string NodeId = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        return instance.getNodeIdBytes();
      }
      /**
       * <code>string NodeId = 2;</code>
       */
      public Builder setNodeId(
          String value) {
        copyOnWrite();
        instance.setNodeId(value);
        return this;
      }
      /**
       * <code>string NodeId = 2;</code>
       */
      public Builder clearNodeId() {
        copyOnWrite();
        instance.clearNodeId();
        return this;
      }
      /**
       * <code>string NodeId = 2;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNodeIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rainmaker.RespSetUserMapping)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RespSetUserMapping();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "status_",
              "nodeId_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RespSetUserMapping> parser = PARSER;
          if (parser == null) {
            synchronized (RespSetUserMapping.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:rainmaker.RespSetUserMapping)
    private static final RespSetUserMapping DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new RespSetUserMapping();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RespSetUserMapping.class, DEFAULT_INSTANCE);
    }
    public static RespSetUserMapping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RespSetUserMapping> PARSER;

    public static com.google.protobuf.Parser<RespSetUserMapping> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RMakerConfigPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rainmaker.RMakerConfigPayload)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
     */
    int getMsgValue();
    /**
     * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
     */
    RMakerConfigMsgType getMsg();

    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    boolean hasCmdSetUserMapping();
    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    CmdSetUserMapping getCmdSetUserMapping();

    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    boolean hasRespSetUserMapping();
    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    RespSetUserMapping getRespSetUserMapping();

    public RMakerConfigPayload.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code rainmaker.RMakerConfigPayload}
   */
  public  static final class RMakerConfigPayload extends
      com.google.protobuf.GeneratedMessageLite<
          RMakerConfigPayload, RMakerConfigPayload.Builder> implements
      // @@protoc_insertion_point(message_implements:rainmaker.RMakerConfigPayload)
      RMakerConfigPayloadOrBuilder {
    private RMakerConfigPayload() {
    }
    private int payloadCase_ = 0;
    private Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      CMD_SET_USER_MAPPING(10),
      RESP_SET_USER_MAPPING(11),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 10: return CMD_SET_USER_MAPPING;
          case 11: return RESP_SET_USER_MAPPING;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      @Override
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    private void clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private int msg_;
    /**
     * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
     */
    @Override
    public int getMsgValue() {
      return msg_;
    }
    /**
     * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
     */
    @Override
    public RMakerConfigMsgType getMsg() {
      RMakerConfigMsgType result = RMakerConfigMsgType.forNumber(msg_);
      return result == null ? RMakerConfigMsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
     */
    private void setMsgValue(int value) {
        msg_ = value;
    }
    /**
     * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
     */
    private void setMsg(RMakerConfigMsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msg_ = value.getNumber();
    }
    /**
     * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
     */
    private void clearMsg() {
      
      msg_ = 0;
    }

    public static final int CMD_SET_USER_MAPPING_FIELD_NUMBER = 10;
    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    @Override
    public boolean hasCmdSetUserMapping() {
      return payloadCase_ == 10;
    }
    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    @Override
    public CmdSetUserMapping getCmdSetUserMapping() {
      if (payloadCase_ == 10) {
         return (CmdSetUserMapping) payload_;
      }
      return CmdSetUserMapping.getDefaultInstance();
    }
    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    private void setCmdSetUserMapping(CmdSetUserMapping value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 10;
    }
    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    private void setCmdSetUserMapping(
        CmdSetUserMapping.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 10;
    }
    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    private void mergeCmdSetUserMapping(CmdSetUserMapping value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 10 &&
          payload_ != CmdSetUserMapping.getDefaultInstance()) {
        payload_ = CmdSetUserMapping.newBuilder((CmdSetUserMapping) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 10;
    }
    /**
     * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
     */
    private void clearCmdSetUserMapping() {
      if (payloadCase_ == 10) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int RESP_SET_USER_MAPPING_FIELD_NUMBER = 11;
    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    @Override
    public boolean hasRespSetUserMapping() {
      return payloadCase_ == 11;
    }
    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    @Override
    public RespSetUserMapping getRespSetUserMapping() {
      if (payloadCase_ == 11) {
         return (RespSetUserMapping) payload_;
      }
      return RespSetUserMapping.getDefaultInstance();
    }
    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    private void setRespSetUserMapping(RespSetUserMapping value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 11;
    }
    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    private void setRespSetUserMapping(
        RespSetUserMapping.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 11;
    }
    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    private void mergeRespSetUserMapping(RespSetUserMapping value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 11 &&
          payload_ != RespSetUserMapping.getDefaultInstance()) {
        payload_ = RespSetUserMapping.newBuilder((RespSetUserMapping) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 11;
    }
    /**
     * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
     */
    private void clearRespSetUserMapping() {
      if (payloadCase_ == 11) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static RMakerConfigPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RMakerConfigPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RMakerConfigPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RMakerConfigPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RMakerConfigPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RMakerConfigPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RMakerConfigPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RMakerConfigPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RMakerConfigPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RMakerConfigPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RMakerConfigPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RMakerConfigPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RMakerConfigPayload prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code rainmaker.RMakerConfigPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RMakerConfigPayload, Builder> implements
        // @@protoc_insertion_point(builder_implements:rainmaker.RMakerConfigPayload)
        RMakerConfigPayloadOrBuilder {
      // Construct using rainmaker.EspRmakerUserMapping.RMakerConfigPayload.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public PayloadCase
          getPayloadCase() {
        return instance.getPayloadCase();
      }

      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }


      /**
       * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
       */
      @Override
      public int getMsgValue() {
        return instance.getMsgValue();
      }
      /**
       * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
       */
      public Builder setMsgValue(int value) {
        copyOnWrite();
        instance.setMsgValue(value);
        return this;
      }
      /**
       * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
       */
      @Override
      public RMakerConfigMsgType getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
       */
      public Builder setMsg(RMakerConfigMsgType value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>.rainmaker.RMakerConfigMsgType msg = 1;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }

      /**
       * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
       */
      @Override
      public boolean hasCmdSetUserMapping() {
        return instance.hasCmdSetUserMapping();
      }
      /**
       * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
       */
      @Override
      public CmdSetUserMapping getCmdSetUserMapping() {
        return instance.getCmdSetUserMapping();
      }
      /**
       * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
       */
      public Builder setCmdSetUserMapping(CmdSetUserMapping value) {
        copyOnWrite();
        instance.setCmdSetUserMapping(value);
        return this;
      }
      /**
       * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
       */
      public Builder setCmdSetUserMapping(
          CmdSetUserMapping.Builder builderForValue) {
        copyOnWrite();
        instance.setCmdSetUserMapping(builderForValue);
        return this;
      }
      /**
       * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
       */
      public Builder mergeCmdSetUserMapping(CmdSetUserMapping value) {
        copyOnWrite();
        instance.mergeCmdSetUserMapping(value);
        return this;
      }
      /**
       * <code>.rainmaker.CmdSetUserMapping cmd_set_user_mapping = 10;</code>
       */
      public Builder clearCmdSetUserMapping() {
        copyOnWrite();
        instance.clearCmdSetUserMapping();
        return this;
      }

      /**
       * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
       */
      @Override
      public boolean hasRespSetUserMapping() {
        return instance.hasRespSetUserMapping();
      }
      /**
       * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
       */
      @Override
      public RespSetUserMapping getRespSetUserMapping() {
        return instance.getRespSetUserMapping();
      }
      /**
       * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
       */
      public Builder setRespSetUserMapping(RespSetUserMapping value) {
        copyOnWrite();
        instance.setRespSetUserMapping(value);
        return this;
      }
      /**
       * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
       */
      public Builder setRespSetUserMapping(
          RespSetUserMapping.Builder builderForValue) {
        copyOnWrite();
        instance.setRespSetUserMapping(builderForValue);
        return this;
      }
      /**
       * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
       */
      public Builder mergeRespSetUserMapping(RespSetUserMapping value) {
        copyOnWrite();
        instance.mergeRespSetUserMapping(value);
        return this;
      }
      /**
       * <code>.rainmaker.RespSetUserMapping resp_set_user_mapping = 11;</code>
       */
      public Builder clearRespSetUserMapping() {
        copyOnWrite();
        instance.clearRespSetUserMapping();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rainmaker.RMakerConfigPayload)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RMakerConfigPayload();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "payload_",
              "payloadCase_",
              "msg_",
              CmdSetUserMapping.class,
              RespSetUserMapping.class,
            };
            String info =
                "\u0000\u0003\u0001\u0000\u0001\u000b\u0003\u0000\u0000\u0000\u0001\f\n<\u0000\u000b" +
                "<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RMakerConfigPayload> parser = PARSER;
          if (parser == null) {
            synchronized (RMakerConfigPayload.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:rainmaker.RMakerConfigPayload)
    private static final RMakerConfigPayload DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new RMakerConfigPayload();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RMakerConfigPayload.class, DEFAULT_INSTANCE);
    }
    public static RMakerConfigPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RMakerConfigPayload> PARSER;

    public static com.google.protobuf.Parser<RMakerConfigPayload> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
