// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: esp_rmaker_claim.proto

package rmaker_claim;

public final class EspRmakerClaim {
  private EspRmakerClaim() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code rmaker_claim.RMakerClaimStatus}
   */
  public enum RMakerClaimStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Success = 0;</code>
     */
    Success(0),
    /**
     * <code>Fail = 1;</code>
     */
    Fail(1),
    /**
     * <code>InvalidParam = 2;</code>
     */
    InvalidParam(2),
    /**
     * <code>InvalidState = 3;</code>
     */
    InvalidState(3),
    /**
     * <code>NoMemory = 4;</code>
     */
    NoMemory(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Success = 0;</code>
     */
    public static final int Success_VALUE = 0;
    /**
     * <code>Fail = 1;</code>
     */
    public static final int Fail_VALUE = 1;
    /**
     * <code>InvalidParam = 2;</code>
     */
    public static final int InvalidParam_VALUE = 2;
    /**
     * <code>InvalidState = 3;</code>
     */
    public static final int InvalidState_VALUE = 3;
    /**
     * <code>NoMemory = 4;</code>
     */
    public static final int NoMemory_VALUE = 4;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RMakerClaimStatus valueOf(int value) {
      return forNumber(value);
    }

    public static RMakerClaimStatus forNumber(int value) {
      switch (value) {
        case 0: return Success;
        case 1: return Fail;
        case 2: return InvalidParam;
        case 3: return InvalidState;
        case 4: return NoMemory;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RMakerClaimStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RMakerClaimStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RMakerClaimStatus>() {
            @Override
            public RMakerClaimStatus findValueByNumber(int number) {
              return RMakerClaimStatus.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return RMakerClaimStatusVerifier.INSTANCE;
    }

    private static final class RMakerClaimStatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new RMakerClaimStatusVerifier();
            @Override
            public boolean isInRange(int number) {
              return RMakerClaimStatus.forNumber(number) != null;
            }
          };

    private final int value;

    private RMakerClaimStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rmaker_claim.RMakerClaimStatus)
  }

  /**
   * Protobuf enum {@code rmaker_claim.RMakerClaimMsgType}
   */
  public enum RMakerClaimMsgType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>TypeCmdClaimStart = 0;</code>
     */
    TypeCmdClaimStart(0),
    /**
     * <code>TypeRespClaimStart = 1;</code>
     */
    TypeRespClaimStart(1),
    /**
     * <code>TypeCmdClaimInit = 2;</code>
     */
    TypeCmdClaimInit(2),
    /**
     * <code>TypeRespClaimInit = 3;</code>
     */
    TypeRespClaimInit(3),
    /**
     * <code>TypeCmdClaimVerify = 4;</code>
     */
    TypeCmdClaimVerify(4),
    /**
     * <code>TypeRespClaimVerify = 5;</code>
     */
    TypeRespClaimVerify(5),
    /**
     * <code>TypeCmdClaimAbort = 6;</code>
     */
    TypeCmdClaimAbort(6),
    /**
     * <code>TypeRespClaimAbort = 7;</code>
     */
    TypeRespClaimAbort(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TypeCmdClaimStart = 0;</code>
     */
    public static final int TypeCmdClaimStart_VALUE = 0;
    /**
     * <code>TypeRespClaimStart = 1;</code>
     */
    public static final int TypeRespClaimStart_VALUE = 1;
    /**
     * <code>TypeCmdClaimInit = 2;</code>
     */
    public static final int TypeCmdClaimInit_VALUE = 2;
    /**
     * <code>TypeRespClaimInit = 3;</code>
     */
    public static final int TypeRespClaimInit_VALUE = 3;
    /**
     * <code>TypeCmdClaimVerify = 4;</code>
     */
    public static final int TypeCmdClaimVerify_VALUE = 4;
    /**
     * <code>TypeRespClaimVerify = 5;</code>
     */
    public static final int TypeRespClaimVerify_VALUE = 5;
    /**
     * <code>TypeCmdClaimAbort = 6;</code>
     */
    public static final int TypeCmdClaimAbort_VALUE = 6;
    /**
     * <code>TypeRespClaimAbort = 7;</code>
     */
    public static final int TypeRespClaimAbort_VALUE = 7;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RMakerClaimMsgType valueOf(int value) {
      return forNumber(value);
    }

    public static RMakerClaimMsgType forNumber(int value) {
      switch (value) {
        case 0: return TypeCmdClaimStart;
        case 1: return TypeRespClaimStart;
        case 2: return TypeCmdClaimInit;
        case 3: return TypeRespClaimInit;
        case 4: return TypeCmdClaimVerify;
        case 5: return TypeRespClaimVerify;
        case 6: return TypeCmdClaimAbort;
        case 7: return TypeRespClaimAbort;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RMakerClaimMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RMakerClaimMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RMakerClaimMsgType>() {
            @Override
            public RMakerClaimMsgType findValueByNumber(int number) {
              return RMakerClaimMsgType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return RMakerClaimMsgTypeVerifier.INSTANCE;
    }

    private static final class RMakerClaimMsgTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new RMakerClaimMsgTypeVerifier();
            @Override
            public boolean isInRange(int number) {
              return RMakerClaimMsgType.forNumber(number) != null;
            }
          };

    private final int value;

    private RMakerClaimMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rmaker_claim.RMakerClaimMsgType)
  }

  public interface PayloadBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rmaker_claim.PayloadBuf)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 Offset = 1;</code>
     */
    int getOffset();

    /**
     * <code>bytes Payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>uint32 TotalLen = 3;</code>
     */
    int getTotalLen();
  }
  /**
   * Protobuf type {@code rmaker_claim.PayloadBuf}
   */
  public  static final class PayloadBuf extends
      com.google.protobuf.GeneratedMessageLite<
          PayloadBuf, PayloadBuf.Builder> implements
      // @@protoc_insertion_point(message_implements:rmaker_claim.PayloadBuf)
      PayloadBufOrBuilder {
    private PayloadBuf() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_;
    /**
     * <code>uint32 Offset = 1;</code>
     */
    @Override
    public int getOffset() {
      return offset_;
    }
    /**
     * <code>uint32 Offset = 1;</code>
     */
    private void setOffset(int value) {
      
      offset_ = value;
    }
    /**
     * <code>uint32 Offset = 1;</code>
     */
    private void clearOffset() {
      
      offset_ = 0;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes Payload = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes Payload = 2;</code>
     */
    private void setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
    }
    /**
     * <code>bytes Payload = 2;</code>
     */
    private void clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
    }

    public static final int TOTALLEN_FIELD_NUMBER = 3;
    private int totalLen_;
    /**
     * <code>uint32 TotalLen = 3;</code>
     */
    @Override
    public int getTotalLen() {
      return totalLen_;
    }
    /**
     * <code>uint32 TotalLen = 3;</code>
     */
    private void setTotalLen(int value) {
      
      totalLen_ = value;
    }
    /**
     * <code>uint32 TotalLen = 3;</code>
     */
    private void clearTotalLen() {
      
      totalLen_ = 0;
    }

    public static PayloadBuf parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PayloadBuf parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PayloadBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PayloadBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PayloadBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PayloadBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PayloadBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PayloadBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PayloadBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static PayloadBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PayloadBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PayloadBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(PayloadBuf prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code rmaker_claim.PayloadBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          PayloadBuf, Builder> implements
        // @@protoc_insertion_point(builder_implements:rmaker_claim.PayloadBuf)
        PayloadBufOrBuilder {
      // Construct using rmaker_claim.EspRmakerClaim.PayloadBuf.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 Offset = 1;</code>
       */
      @Override
      public int getOffset() {
        return instance.getOffset();
      }
      /**
       * <code>uint32 Offset = 1;</code>
       */
      public Builder setOffset(int value) {
        copyOnWrite();
        instance.setOffset(value);
        return this;
      }
      /**
       * <code>uint32 Offset = 1;</code>
       */
      public Builder clearOffset() {
        copyOnWrite();
        instance.clearOffset();
        return this;
      }

      /**
       * <code>bytes Payload = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getPayload() {
        return instance.getPayload();
      }
      /**
       * <code>bytes Payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPayload(value);
        return this;
      }
      /**
       * <code>bytes Payload = 2;</code>
       */
      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }

      /**
       * <code>uint32 TotalLen = 3;</code>
       */
      @Override
      public int getTotalLen() {
        return instance.getTotalLen();
      }
      /**
       * <code>uint32 TotalLen = 3;</code>
       */
      public Builder setTotalLen(int value) {
        copyOnWrite();
        instance.setTotalLen(value);
        return this;
      }
      /**
       * <code>uint32 TotalLen = 3;</code>
       */
      public Builder clearTotalLen() {
        copyOnWrite();
        instance.clearTotalLen();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rmaker_claim.PayloadBuf)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new PayloadBuf();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "offset_",
              "payload_",
              "totalLen_",
            };
            String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\n" +
                "\u0003\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<PayloadBuf> parser = PARSER;
          if (parser == null) {
            synchronized (PayloadBuf.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:rmaker_claim.PayloadBuf)
    private static final PayloadBuf DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new PayloadBuf();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PayloadBuf.class, DEFAULT_INSTANCE);
    }
    public static PayloadBuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PayloadBuf> PARSER;

    public static com.google.protobuf.Parser<PayloadBuf> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RespPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rmaker_claim.RespPayload)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
     */
    RMakerClaimStatus getStatus();

    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    boolean hasBuf();
    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    PayloadBuf getBuf();
  }
  /**
   * Protobuf type {@code rmaker_claim.RespPayload}
   */
  public  static final class RespPayload extends
      com.google.protobuf.GeneratedMessageLite<
          RespPayload, RespPayload.Builder> implements
      // @@protoc_insertion_point(message_implements:rmaker_claim.RespPayload)
      RespPayloadOrBuilder {
    private RespPayload() {
    }
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
     */
    @Override
    public RMakerClaimStatus getStatus() {
      RMakerClaimStatus result = RMakerClaimStatus.forNumber(status_);
      return result == null ? RMakerClaimStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
     */
    private void setStatus(RMakerClaimStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int BUF_FIELD_NUMBER = 2;
    private PayloadBuf buf_;
    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    @Override
    public boolean hasBuf() {
      return buf_ != null;
    }
    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    @Override
    public PayloadBuf getBuf() {
      return buf_ == null ? PayloadBuf.getDefaultInstance() : buf_;
    }
    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    private void setBuf(PayloadBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      buf_ = value;
      
      }
    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    private void setBuf(
        PayloadBuf.Builder builderForValue) {
      buf_ = builderForValue.build();
      
    }
    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeBuf(PayloadBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (buf_ != null &&
          buf_ != PayloadBuf.getDefaultInstance()) {
        buf_ =
          PayloadBuf.newBuilder(buf_).mergeFrom(value).buildPartial();
      } else {
        buf_ = value;
      }
      
    }
    /**
     * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
     */
    private void clearBuf() {  buf_ = null;
      
    }

    public static RespPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RespPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RespPayload prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code rmaker_claim.RespPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RespPayload, Builder> implements
        // @@protoc_insertion_point(builder_implements:rmaker_claim.RespPayload)
        RespPayloadOrBuilder {
      // Construct using rmaker_claim.EspRmakerClaim.RespPayload.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
       */
      @Override
      public RMakerClaimStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
       */
      public Builder setStatus(RMakerClaimStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.RMakerClaimStatus Status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
       */
      @Override
      public boolean hasBuf() {
        return instance.hasBuf();
      }
      /**
       * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
       */
      @Override
      public PayloadBuf getBuf() {
        return instance.getBuf();
      }
      /**
       * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
       */
      public Builder setBuf(PayloadBuf value) {
        copyOnWrite();
        instance.setBuf(value);
        return this;
        }
      /**
       * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
       */
      public Builder setBuf(
          PayloadBuf.Builder builderForValue) {
        copyOnWrite();
        instance.setBuf(builderForValue);
        return this;
      }
      /**
       * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
       */
      public Builder mergeBuf(PayloadBuf value) {
        copyOnWrite();
        instance.mergeBuf(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.PayloadBuf Buf = 2;</code>
       */
      public Builder clearBuf() {  copyOnWrite();
        instance.clearBuf();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rmaker_claim.RespPayload)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RespPayload();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "status_",
              "buf_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RespPayload> parser = PARSER;
          if (parser == null) {
            synchronized (RespPayload.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:rmaker_claim.RespPayload)
    private static final RespPayload DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new RespPayload();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RespPayload.class, DEFAULT_INSTANCE);
    }
    public static RespPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RespPayload> PARSER;

    public static com.google.protobuf.Parser<RespPayload> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RMakerClaimPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rmaker_claim.RMakerClaimPayload)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
     */
    int getMsgValue();
    /**
     * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
     */
    RMakerClaimMsgType getMsg();

    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    boolean hasCmdPayload();
    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    PayloadBuf getCmdPayload();

    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    boolean hasRespPayload();
    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    RespPayload getRespPayload();

    public RMakerClaimPayload.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code rmaker_claim.RMakerClaimPayload}
   */
  public  static final class RMakerClaimPayload extends
      com.google.protobuf.GeneratedMessageLite<
          RMakerClaimPayload, RMakerClaimPayload.Builder> implements
      // @@protoc_insertion_point(message_implements:rmaker_claim.RMakerClaimPayload)
      RMakerClaimPayloadOrBuilder {
    private RMakerClaimPayload() {
    }
    private int payloadCase_ = 0;
    private Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      CMDPAYLOAD(10),
      RESPPAYLOAD(11),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 10: return CMDPAYLOAD;
          case 11: return RESPPAYLOAD;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      @Override
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    private void clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private int msg_;
    /**
     * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
     */
    @Override
    public int getMsgValue() {
      return msg_;
    }
    /**
     * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
     */
    @Override
    public RMakerClaimMsgType getMsg() {
      RMakerClaimMsgType result = RMakerClaimMsgType.forNumber(msg_);
      return result == null ? RMakerClaimMsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
     */
    private void setMsgValue(int value) {
        msg_ = value;
    }
    /**
     * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
     */
    private void setMsg(RMakerClaimMsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msg_ = value.getNumber();
    }
    /**
     * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
     */
    private void clearMsg() {
      
      msg_ = 0;
    }

    public static final int CMDPAYLOAD_FIELD_NUMBER = 10;
    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    @Override
    public boolean hasCmdPayload() {
      return payloadCase_ == 10;
    }
    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    @Override
    public PayloadBuf getCmdPayload() {
      if (payloadCase_ == 10) {
         return (PayloadBuf) payload_;
      }
      return PayloadBuf.getDefaultInstance();
    }
    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    private void setCmdPayload(PayloadBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 10;
    }
    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    private void setCmdPayload(
        PayloadBuf.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 10;
    }
    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    private void mergeCmdPayload(PayloadBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 10 &&
          payload_ != PayloadBuf.getDefaultInstance()) {
        payload_ = PayloadBuf.newBuilder((PayloadBuf) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 10;
    }
    /**
     * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
     */
    private void clearCmdPayload() {
      if (payloadCase_ == 10) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int RESPPAYLOAD_FIELD_NUMBER = 11;
    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    @Override
    public boolean hasRespPayload() {
      return payloadCase_ == 11;
    }
    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    @Override
    public RespPayload getRespPayload() {
      if (payloadCase_ == 11) {
         return (RespPayload) payload_;
      }
      return RespPayload.getDefaultInstance();
    }
    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    private void setRespPayload(RespPayload value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 11;
    }
    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    private void setRespPayload(
        RespPayload.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 11;
    }
    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    private void mergeRespPayload(RespPayload value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 11 &&
          payload_ != RespPayload.getDefaultInstance()) {
        payload_ = RespPayload.newBuilder((RespPayload) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 11;
    }
    /**
     * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
     */
    private void clearRespPayload() {
      if (payloadCase_ == 11) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static RMakerClaimPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RMakerClaimPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RMakerClaimPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RMakerClaimPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RMakerClaimPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RMakerClaimPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RMakerClaimPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RMakerClaimPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RMakerClaimPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RMakerClaimPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RMakerClaimPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RMakerClaimPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RMakerClaimPayload prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code rmaker_claim.RMakerClaimPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RMakerClaimPayload, Builder> implements
        // @@protoc_insertion_point(builder_implements:rmaker_claim.RMakerClaimPayload)
        RMakerClaimPayloadOrBuilder {
      // Construct using rmaker_claim.EspRmakerClaim.RMakerClaimPayload.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public PayloadCase
          getPayloadCase() {
        return instance.getPayloadCase();
      }

      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }


      /**
       * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
       */
      @Override
      public int getMsgValue() {
        return instance.getMsgValue();
      }
      /**
       * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
       */
      public Builder setMsgValue(int value) {
        copyOnWrite();
        instance.setMsgValue(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
       */
      @Override
      public RMakerClaimMsgType getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
       */
      public Builder setMsg(RMakerClaimMsgType value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.RMakerClaimMsgType msg = 1;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }

      /**
       * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
       */
      @Override
      public boolean hasCmdPayload() {
        return instance.hasCmdPayload();
      }
      /**
       * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
       */
      @Override
      public PayloadBuf getCmdPayload() {
        return instance.getCmdPayload();
      }
      /**
       * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
       */
      public Builder setCmdPayload(PayloadBuf value) {
        copyOnWrite();
        instance.setCmdPayload(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
       */
      public Builder setCmdPayload(
          PayloadBuf.Builder builderForValue) {
        copyOnWrite();
        instance.setCmdPayload(builderForValue);
        return this;
      }
      /**
       * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
       */
      public Builder mergeCmdPayload(PayloadBuf value) {
        copyOnWrite();
        instance.mergeCmdPayload(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.PayloadBuf cmdPayload = 10;</code>
       */
      public Builder clearCmdPayload() {
        copyOnWrite();
        instance.clearCmdPayload();
        return this;
      }

      /**
       * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
       */
      @Override
      public boolean hasRespPayload() {
        return instance.hasRespPayload();
      }
      /**
       * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
       */
      @Override
      public RespPayload getRespPayload() {
        return instance.getRespPayload();
      }
      /**
       * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
       */
      public Builder setRespPayload(RespPayload value) {
        copyOnWrite();
        instance.setRespPayload(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
       */
      public Builder setRespPayload(
          RespPayload.Builder builderForValue) {
        copyOnWrite();
        instance.setRespPayload(builderForValue);
        return this;
      }
      /**
       * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
       */
      public Builder mergeRespPayload(RespPayload value) {
        copyOnWrite();
        instance.mergeRespPayload(value);
        return this;
      }
      /**
       * <code>.rmaker_claim.RespPayload respPayload = 11;</code>
       */
      public Builder clearRespPayload() {
        copyOnWrite();
        instance.clearRespPayload();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rmaker_claim.RMakerClaimPayload)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RMakerClaimPayload();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "payload_",
              "payloadCase_",
              "msg_",
              PayloadBuf.class,
              RespPayload.class,
            };
            String info =
                "\u0000\u0003\u0001\u0000\u0001\u000b\u0003\u0000\u0000\u0000\u0001\f\n<\u0000\u000b" +
                "<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RMakerClaimPayload> parser = PARSER;
          if (parser == null) {
            synchronized (RMakerClaimPayload.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:rmaker_claim.RMakerClaimPayload)
    private static final RMakerClaimPayload DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new RMakerClaimPayload();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RMakerClaimPayload.class, DEFAULT_INSTANCE);
    }
    public static RMakerClaimPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RMakerClaimPayload> PARSER;

    public static com.google.protobuf.Parser<RMakerClaimPayload> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
